# Generated by Django 6.0.4 on 2026-04-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('light_id', models.CharField(blank=True, max_length=10, null=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('light_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('device_ip', models.GenericIPAddressField()),
                ('device_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('light_id', models.CharField(db_index=True, max_length=10)),
                ('action', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('ACCESS', 'ACCESS')], max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='django', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_floor', models.CharField(default='B', max_length=1)),
                ('max_room_number', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_hash', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_ip', models.GenericIPAddressField()),
                ('light', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.light')),
            ],
        ),
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_ip', models.GenericIPAddressField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.light')),
            ],
        ),
    ]
